### ISSUE TITLE
AfricasTalking service error when testing locally

### ISSUE THREAD

**Issue by jojostx** [laravel-notification-channels/africastalking#15]
Hello Ossy, @ossycodes  

I get this error whenever I make a post through laravel using the bulk sms service:

`[2022-02-24 15:12:12] local.ERROR: AfricasTalking service responded with an error: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://api.africastalking.com/version1/messaging`

Ps: I'm currently using laravel 8 and PHP 8.1

**Comment by ossycodes** [comment]
@jojostx It's working fine, please ensure you have the right AT_USERNAME and AT_KEY and your internet connection is good
