### ISSUE TITLE
Channel Launch

### ISSUE THREAD

**Issue by atymic** [laravel-notification-channels/africastalking#2]
- [x] Code Review
- [x] Add @ossycodes as repo admin
- [x] Add @ossycodes to github org
- [x] Add to website
- [x] Create packagist package
- [x] Travis
- [x] Style CI
- [x] Scrutinizer 
- [x] Add badges

**Comment by ossycodes** [comment]
Although I have been given admin access, I don't know why I can't submit the package to packagist? Please Help. @atymic 

![pkgissue](https://user-images.githubusercontent.com/55060799/76840167-02577f00-6837-11ea-9589-668734efabeb.PNG)

**Comment by atymic** [comment]
Submitted
https://packagist.org/packages/laravel-notification-channels/africastalking

**Comment by atymic** [comment]
Good to tag the first release when you're ready and close this issue :)

**Comment by ossycodes** [comment]
Thanks alot! @atymic
