### ISSUE TITLE
Support sandbox environment

### ISSUE THREAD

**Issue by njoguamos** [laravel-notification-channels/africastalking#21]
At the moment, there is no way of using Africa's Talking sandbox environment.

The sandbox is good for testing locally or in CI environments.

**Comment by SamuelMwangiW** [comment]
Hi @njoguamos. You should be able to use sandbox by setting `AT_USERNAME` to "sandbox" instead of your live app username

```env
AT_USERNAME="sandbox"
AT_KEY="yoursandboxapikey"
```

**Comment by njoguamos** [comment]
Thank you. I will consider that.
